use role sysadmin;
USE SCHEMA PUNE;

CREATE OR REPLACE TABLE STATE_LOSS_DETAIL
(
STATE_CODE VARCHAR(2),
MEMBER_ID NUMBER(3),
LOSS_VALUE NUMBER
);
--DROP TABLE STATE_LOSS_DETAIL

INSERT INTO STATE_LOSS_DETAIL VALUES
('NY',1,100),('NY',2,200),('NY',3,300),
('TX',4,100),('TX',5,200),
('CA',6,100),('CA',7,200);

--CREATE AN AGGREGATION POLICY IN SUCH A WAY THAT IF A GROUP HAS LESS THAN 3 VALUE THEN IT WONT BE CONSIDERED AS INDEPENDENT GROUP BUT AS REMAINDER GROUP

CREATE AGGREGATION POLICY AGG_POL_MIN_3
  AS () RETURNS AGGREGATION_CONSTRAINT -> AGGREGATION_CONSTRAINT(MIN_GROUP_SIZE => 3);

ALTER TABLE STATE_LOSS_DETAIL SET AGGREGATION POLICY AGG_POL_MIN_3;

---TRY QUERIENG

SELECT * FROM STATE_LOSS_DETAIL ;

SELECT STATE_CODE,MAX(LOSS_VALUE) FROM STATE_LOSS_DETAIL GROUP BY STATE_CODE;

explain SELECT STATE_CODE,AVG(LOSS_VALUE) FROM STATE_LOSS_DETAIL GROUP BY STATE_CODE;

ALTER TABLE STATE_LOSS_DETAIL UNSET AGGREGATION POLICY ;

---------------------------------------------------------------------

--Create a projection policy for LOSS_VALUE

    CREATE OR REPLACE PROJECTION POLICY PROJ_POLICY_LOSS_VAL AS ()
    RETURNS PROJECTION_CONSTRAINT ->
    CASE
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN PROJECTION_CONSTRAINT(ALLOW => TRUE)
        ELSE PROJECTION_CONSTRAINT(ALLOW => FALSE)
    END;

    ALTER TABLE STATE_LOSS_DETAIL MODIFY COLUMN LOSS_VALUE SET PROJECTION POLICY PROJ_POLICY_LOSS_VAL;

    select * from STATE_LOSS_DETAIL ;

    select * exclude LOSS_VALUE from STATE_LOSS_DETAIL ;

    use role accountadmin;

    select * from STATE_LOSS_DETAIL ;

    use role sysadmin;

    ALTER TABLE STATE_LOSS_DETAIL MODIFY COLUMN LOSS_VALUE UNSET PROJECTION POLICY;

-----------------------------------------------------------------------

--Create a privacy policy for differential privacy

CREATE OR REPLACE PRIVACY POLICY 
  DPP_LOSS AS () RETURNS privacy_budget ->
  CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN no_privacy_policy()   
    ELSE privacy_budget(budget_name => 'Budget_1')
END;

ALTER TABLE STATE_LOSS_DETAIL
ADD PRIVACY POLICY DPP_LOSS 
  ENTITY KEY (MEMBER_ID);

  ALTER TABLE STATE_LOSS_DETAIL ALTER (
    COLUMN STATE_CODE 
        SET PRIVACY DOMAIN IN ('NY', 'TX' , 'CA'));

use role ACCOUNTADMIN; 

SELECT COUNT(DISTINCT MEMBER_ID) FROM STATE_LOSS_DETAIL WHERE STATE_CODE='NY';

USE ROLE SYSADMIN;

SELECT COUNT(DISTINCT MEMBER_ID) FROM STATE_LOSS_DETAIL WHERE STATE_CODE='NY';

ALTER TABLE STATE_LOSS_DETAIL DROP PRIVACY POLICY DPP_LOSS;


--COURTESY TO CESAR FOR HIS MEDIUM BLOG
-- https://medium.com/sdg-group/snowflake-security-using-diferential-privay-policy-c76a8511bf16